### ISSUE TITLE
Cannot run native code with restricted IO access.

### ISSUE THREAD

**Issue by zolstein** [graalvm/graalpython#123]
Running on 19.3.0 on MacOS (Mojave 10.14.6)

I'm trying to get the pytz library working in contexts in a java server. We can't allow the contexts to have unrestricted IO on the system. I've installed pytz in the lib-python/3/sites-packages directory. (I had to manually copy it from my ~/.local directory; does the ginstall script have a good way to install there directly?) Thus far I've run up against two main issues when running without unrestricted IO:

1. When searching for files in the internal file system, the PosixModueBuiltins refuses to recognize .dylib files; it only allows .py and .pyc files. I've worked around this by adding .dylib to the PythonLanguage.DEFAULT_PYTHON_EXTENSIONS array. I don't know if you'd accept upstreaming that change, or if you'd want to do something cleverer. (E.g. somehow only allow it if the context got configured with allowNativeAccess(true)?) It seems safe to me because the context will still only execute the native code if the context has native access / polyglot access configured correctly, but I don't have enough context to feel confident of that.

2. (Possibly/probably MacOS specific?) Some piece of code (I haven't isolated which; probably several; probably native) wants to load the file /usr/lib/libSystem.B.dylib. I have yet to find a good way to work around this without enabling unrestricted IO access; either by specifically allowing access to this file or by having it reference a copy in some language directory.  Possibly this change would need to happen in sulong? I don't know enough about compiling/running native code to make a good guess as to how to solve this.

**Comment by timfel** [comment]
Fundamentally, if you allow native access you pretty much have to allow all access - native code can do whatever it wants, after all. If you use Enterprise Edition, you can use the fully managed LLVM execution, and then you need neither native access nor IO permissions.

We currently don't support installing into the internal filesystem. The recommended approach is to allow IO access, but install a custom FileSystem when you create the context. All filesystem access in Python goes through the Graal Context filesystem, so that's the intercession point you should use there. This approach would also allow you to intercept the access to `libSystem.B.dylib` and use a e.g. a whitelist to serve it.

You shouldn't extend `DEFAULT_PYTHON_EXTENSIONS` - a dylib is *not* a Python file, it's a *LLVM* file. The way that importing native modules works on Python is by querying Sulong for its allowed extensions (see the `imp` module implementation).

**Comment by zolstein** [comment]
> Fundamentally, if you allow native access you pretty much have to allow all access - native code can do whatever it wants, after all.

... Except, I would hope, have unrestricted access to the real filesystem, the ability to spawn processors/threads, and the other syscall-like operations that the Context has tools to restrict, right?

> The recommended approach is to allow IO access, but install a custom FileSystem when you create the context.

I basically wound up doing this, but it was painful. Because the Truffle API doesn't provide any public implementations of the FileSystem interface, I basically needed to copy the FileSystems class directly into my codebase and hack at it to give me the custom FileSystem I want. I've opened a separate issue in the main Graal repo about making this easier.

> We currently don't support installing into the internal filesystem.

Then why does the lib-python/3/sites-packages directory exist, with the comment that `This directory exists so that 3rd party packages can be installed here.`?

> The way that importing native modules works on Python is by querying Sulong for its allowed extensions (see the imp module implementation).

Okay, but when I actually try doing this (without allowIO or the sort of gross FileSystem fix), some piece of the /importlib/_bootstrap code tries to call posix.stat on the .../lib-graalpython/modules/_struct.graalpython-native-x86_64-darwin.dylib file. Because the implementation of posix.stat only looks for py and pyc files in the default filesystem, it instead reports `ModuleNotFoundError: No module named '_struct'`. This failure happens before we get to the imp implementation. I don't have enough context on graalpython specifically or truffle in general as to why the code works the way it does to make a strong case, so I can only appeal to a general feeling that this is not the right behavior. I think it makes sense that these files, which while not _actually_ python code are effectively treated like python code in certain cases, would be visible to the internal filesystem in the same way as python files.

**Comment by timfel** [comment]
> ... Except, I would hope, have unrestricted access to the real filesystem, the ability to spawn processors/threads, and the other syscall-like operations that the Context has tools to restrict, right?

No. Native is really native, there's no sandboxing or anything. If you want to restrict what C code can do, you need to run it with Sulong managed mode on GraalVM enterprise edition.

> > We currently don't support installing into the internal filesystem.
> 
> Then why does the lib-python/3/sites-packages directory exist, with the comment that `This directory exists so that 3rd party packages can be installed here.`?

I didn't even notice that :) The `lib-python` folder is a straight up copy from CPython, we try not to touch it unless we don't support something, yet.

> Okay, but when I actually try doing this (without allowIO or the sort of gross FileSystem fix), some piece of the /importlib/_bootstrap code tries to call posix.stat on the .../lib-graalpython/modules/_struct.graalpython-native-x86_64-darwin.dylib file. Because the implementation of posix.stat only looks for py and pyc files in the default filesystem, it instead reports `ModuleNotFoundError: No module named '_struct'`. This failure happens before we get to the imp implementation. I don't have enough context on graalpython specifically or truffle in general as to why the code works the way it does to make a strong case, so I can only appeal to a general feeling that this is not the right behavior. I think it makes sense that these files, which while not _actually_ python code are effectively treated like python code in certain cases, would be visible to the internal filesystem in the same way as python files.

The entire import logic in Python is written in the Python standard library. We don't actually implement anything related to importing, other than mapping the `import` syntax to an `__import__` call. So the way it works is exactly how it works on CPython (including `stat` calls and all that) since we don't want to touch that. The stat calls you're seeing are expected, because the Python file importer is queried before the "extension" file importer, which loads C extension modules.

**Comment by msimacek** [comment]
Hi @zolstein, there hasn't been any recent activity on this ticket. It seems your questions have been answered, do you have any objections to closing it?

**Comment by zolstein** [comment]
No objection.
