### ISSUE TITLE
Implement `mmap`

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/graalpython#45]

**Comment by fangerer** [comment]
Hi Kolanich, 
thanks again for reporting. Since module `mmap` is directly using the POSIX syscall `mmap`, it's probably not easy for us to implement the module.
The problem is that we are using our own filesystem abstraction and can't do this operation in the same way.
However, we might be able to emulate the behavior reasonably.
But as usual, I can't promise anything.

**Comment by KOLANICH** [comment]
>However, we might be able to emulate the behavior reasonably.

I'm afraid it defeats the purpose of ever using memory-mapped io. What is the problem to pass it through the FS abstraction you have mentioned?

**Comment by fangerer** [comment]
Maybe my answer was a bit misleading: I just meant that we cannot directly use the syscall `mmap` as you can do from a C implementation because our host language is Java. But we can implement this using `java.nio` which will in the end be very similar. But it may be that we cannot offer same flexibility looking at all the flags one can specify when using mmap.

So, I think performance won't be the problem.

**Comment by tdbgamer** [comment]
What about something like JNA?

https://github.com/java-native-access/jna

**Comment by timfel** [comment]
@tdbgamer we don't want to call any native code directly like this. We always want to ensure this Python implementation can be fully sandboxed on the Java level, so there will always be a bit of a mismatch.

**Comment by timfel** [comment]
`mmap` support is included in the latest releases.

**Comment by KOLANICH** [comment]
Thanks everybody involved into implementing this.
