### ISSUE TITLE
Graal.Python executable name inconsistent with other GraalVM languages

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#71]
I suggest to rename the `graalpython` executable to `python3` and to add `python` as an alias.

The current naming scheme is inconsistent with all official GraalVM languages (e.g. TruffleRuby -> `irb`/`ruby`, fastR -> `R`, Graal.JS -> `js`/`npm`/`node`, ...). This is especially confusing for beginners because they must know that Python is provided through the `graalpython` binary and it's harder to use Graal.Python as a drop-in replacement (it's not sufficient to adjust `$PATH`).

**Comment by lukasstadler** [comment]
Hi Fabio! Since we ran into trouble from time to time because our Python implementation is not complete enough yet to run tools like `mx`, we decided to use a different name for the executable. That way, it's possible to put the `bin` directory in `$PATH` and still use a different python to run these tools.

**Comment by fniephaus** [comment]
Thanks for the info, @lukasstadler! @timfel already mentioned that this would cause issues on the CI servers. So it's called `graalpython` for now, because it's still considered "too experimental" which makes sense. But hopefully it's not too soon until Graal.Python can run `mx` and supports `sockets`, etc. :)

**Comment by lukasstadler** [comment]
We're working on it ;-)
