### ISSUE TITLE
Passing Cyrillic strings to gethostbyname doesn't work

### ISSUE THREAD

**Issue by Kolpa** [graalvm/graalpython#94]
the following python call

```py
domain = 'испытание.pythontest.net'
socket.gethostbyname(domain)
```

results in the following data on Java side
![image](https://user-images.githubusercontent.com/1751900/62295142-afc67f80-b46c-11e9-8489-cdeaaa944c12.png)

**Comment by timfel** [comment]
Looks like we need to start taking encodings more seriously. Thanks for the example!

**Comment by msimacek** [comment]
There's no problem in passing the string between Python and Java. The weird characters you observe are most likely caused by a missing font in your IDE. There's a different problem. Domain names may only contain ASCII characters, but there is a mechanism called IDN that is used to encode Unicode characters as ASCII. CPython does this conversion in `gethostbyname`, but our implementation was missing it. I can fix that.
